public_repo_path=imgly/starterkit-video-editor-android
public_repo_description=Video Editor starter kit that is built on top of the Creative Editor SDK.
gradle_project_name=starter-kit-video
app_name=Video Editor
package_suffix=video
